# Generated by Django 5.0 on 2023-12-29 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='member',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
